all:
	gcc src/add.c -c -o bin/add.o
	gcc src/delete.c -c -o bin/delete.o
	gcc src/get.c -c -o bin/get.o
	gcc src/getAll.c -c -o bin/getAll.o
	gcc src/search.c -c -o bin/search.o
	gcc src/main.c -c -o bin/main.o
	gcc bin/*.o -o main